name: Robot Creador OCI
on:
  workflow_dispatch:

jobs:
  crear-servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostico Sin Censura
        run: |
          pip install oci-cli
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_ID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_ID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{ secrets.OCI_KEY_CONTENT }}" > ~/.oci/key.pem
          chmod 600 ~/.oci/key.pem
          /home/runner/.local/bin/oci iam region list
